name: release-it

on:
  push:
    branches:
      - master

jobs:
  release:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: git checkout master

    - name: set .npmrc
      run: echo "${NPMRC}" > ~/.npmrc
      env:
        NPMRC: ${{ secrets.NPMRC }}

    - run: |
        git config --global user.name "nekottyo"
        git config --global user.email "nekottyo@users.noreply.github.com"

    - run: npm install


    - name: release-it
      run: npm run release -- patch --ci --no-git.requireCleanWorkingDir
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
